### ISSUE TITLE
Create a data model for price tracking

### ISSUE THREAD

**Issue by hahuang65** [BitSmithy/price_tracker#9]
We'll need a data model to be able to track the price of items.

Things we'll want to accommodate:
1) An item's price is tracked such that we can find a historical trend from the present until the point it started being tracked.
2) The pricing data is structured such that we can look at a universal price, or segregate by retailer.

Let's just focus on the model and database schemas for this ticket.

**Comment by aghalarp** [comment]
It might be simplistic, but the PriceHistory model below should be able to take care of both requirements. As a reminder, each RetailerProduct represents a product sold by a specific retailer. The one-to-many relationship between RetailerProduct and PriceHistory therefore allows us to look at pricing history for a given product sold at a certain retailer. We'll want to create an index on the timestamp field. We can utilize this data model to generate other interesting statistics, such as average prices, lowest/highest prices across retailers for a given product, etc. 

![pricetracker erd 4](https://user-images.githubusercontent.com/5334478/50106420-ce3d7a80-01fd-11e9-8292-e909fe55bac3.png)

**Comment by aghalarp** [comment]
Satisfied by #20
